# Generated by Django 4.2 on 2024-08-12 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyecto', '0002_measure'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Measure',
        ),
    ]
